version: '{build}-{branch}'
image: Visual Studio 2017

skip_commits:
  files:
    - '**/*.md'

build_script:
- ps: .\build.ps1

after_build:
- ps: .\pack.ps1

artifacts:
- path: '**\artifacts\nuget\*.nupkg'
  name: NuGet
  
deploy:
- provider: NuGet
  api_key:
    secure: ElAeMRSkpq3xUZ1TbenrrObh1zB/p62I5ICs92heJnTvkcl4Znc5o36vCyqcOK49
  on:
    appveyor_repo_tag: true